### ISSUE TITLE
Some apps affected by ignoring permission

### ISSUE THREAD

**Issue by marcher233** [Jiangyiqun/android_background_ignore#3]
1. Action button on notification bar won't work. Affected app: Inbox (com.google.android.apps.inbox).
2. Alarm won't ring. Alarm app won't wake up by Android OS. Affected app: Sleep as Android (com.urbandroid.sleep).

**Comment by liudongmiao** [comment]
@marcher233 

Yes, `RUN_IN_BACKGROUND` can do something, but not all things. For your question:

1. some app can still be running. Android introduces `PROCESS_STATE_BACKUP`, it means only `IMPORTANCE_SERVICE` and `IMPORTANCE_BACKGROUND` can be regards as background, if the app has other process state/importance, it's still living.

2. `RUN_IN_BACKGROUND` blocks Alarm, so please don't block Alarm app.

**Comment by liudongmiao** [comment]
@marcher233 You may want to try Brevent: https://play.google.com/store/apps/details?id=me.piebridge.brevent
