### ISSUE TITLE
诚邀测试新版黑域

### ISSUE THREAD

**Issue by liudongmiao** [Jiangyiqun/android_background_ignore#4]
你好，我是前阻止运行，黑域补丁版作者，现在邀请你测试黑域普通版。

黑域普通版利用adb shell的权限，开启一个进程，对于阻止列表中的程序设置 run_in_background，同时有其它优化。简单来说：

1. 动态设置 run_in_background
2. 对于某些压不住的，如 bind service，会有其它处理，即判断在一定时间内是否打开了 activity，如果没有，强行停止它。
3. 其它好多好多优化，大致会使用这种手段代替阻止运行，黑域补丁版的事。

**Comment by jackjyq** [comment]
感谢邀请，我的邮箱是jackjyq@outlook.com

**Comment by liudongmiao** [comment]
请直接去酷安或者谷歌市场下载
